services:
  server:
    depends_on:
      - db
    build: .
    ports:
      - "8000:8000"
    networks:
      - cs

  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./migrations/000001_init_up.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - cs

networks:
  cs: